package com.mycompany.projekbasdat;

import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ACER
 */
public class LandingPage extends javax.swing.JPanel {

    /**
     * Creates new form LandingPage
     */
    private DataBaseConnection DB;

    public LandingPage() {
        initComponents();

        // Focus listener for username field
        Loginusername1.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (Loginusername1.getText().equals("Masukkan di sini...")) {
                    Loginusername1.setText(""); // Clear default text
                    Loginusername1.setForeground(java.awt.Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (Loginusername1.getText().trim().isEmpty()) {
                    Loginusername1.setText("Masukkan di sini..."); // Restore default text if empty
                    Loginusername1.setForeground(java.awt.Color.GRAY);
                }
            }
        });

        // Focus listener for password field
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (new String(jPasswordField1.getPassword()).equals("Masukkan di sini...")) {
                    jPasswordField1.setText(""); // Clear default text
                    jPasswordField1.setForeground(java.awt.Color.BLACK);
                    jPasswordField1.setEchoChar('*'); // Mask password input
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (new String(jPasswordField1.getPassword()).trim().isEmpty()) {
                    jPasswordField1.setText("Masukkan di sini..."); // Restore default text if empty
                    jPasswordField1.setForeground(java.awt.Color.GRAY);
                    jPasswordField1.setEchoChar((char) 0); // Show text instead of masking
                }
            }
        });

        // Key listener for Enter key in the username field
        Loginusername1.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    // If username field is empty or still has default text, focus moves to password
                    if (Loginusername1.getText().equals("Masukkan di sini...")
                            || Loginusername1.getText().trim().isEmpty()) {
                        jPasswordField1.requestFocus();
                    } else {
                        // If username is filled and password field is still on default, move focus to
                        // password
                        if (new String(jPasswordField1.getPassword()).equals("Masukkan di sini...")
                                || new String(jPasswordField1.getPassword()).trim().isEmpty()) {
                            jPasswordField1.requestFocus();
                        }
                    }
                }
            }
        });

        // Key listener for Enter key in the password field
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    // If password field is filled, trigger login, otherwise, move focus to password
                    if (new String(jPasswordField1.getPassword()).equals("Masukkan di sini...")
                            || new String(jPasswordField1.getPassword()).trim().isEmpty()) {
                        jPasswordField1.requestFocus(); // Keeps focus on password
                    } else {
                        jButton1.doClick(); // Trigger login when password is filled
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jFrame4 = new javax.swing.JFrame();
        SelamatDatangTeks = new javax.swing.JTextField();
        Loginusername1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        SelamatDatangTeks2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE));
        jFrame1Layout.setVerticalGroup(
                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE));

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
                jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE));
        jFrame2Layout.setVerticalGroup(
                jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE));

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
                jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE));
        jFrame3Layout.setVerticalGroup(
                jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE));

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
                jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE));
        jFrame4Layout.setVerticalGroup(
                jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE));

        setBackground(new java.awt.Color(255, 255, 255));

        SelamatDatangTeks.setFont(new java.awt.Font("Javanese Text", 2, 14)); // NOI18N
        SelamatDatangTeks.setText("Pilihan Tepat Mencari Mobil");
        SelamatDatangTeks.setBorder(null);
        SelamatDatangTeks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelamatDatangTeksActionPerformed(evt);
            }
        });

        Loginusername1.setForeground(new java.awt.Color(204, 204, 204));
        Loginusername1.setText("Masukkan di sini...");
        Loginusername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Loginusername1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Username");

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Password");

        SelamatDatangTeks2.setFont(new java.awt.Font("Javanese Text", 1, 24)); // NOI18N
        SelamatDatangTeks2.setText("Selamat Datang Di Car Check");
        SelamatDatangTeks2.setBorder(null);
        SelamatDatangTeks2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelamatDatangTeks2ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/projekbasdat/8150325.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(230, 230, 230)
                                                .addComponent(SelamatDatangTeks, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(153, 153, 153)
                                                .addComponent(SelamatDatangTeks2,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 293,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(Loginusername1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 240,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jPasswordField1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 240,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3))))
                                .addContainerGap(53, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(SelamatDatangTeks2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SelamatDatangTeks, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(Loginusername1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 199,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(23, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // System.out.println(triggerLogin()[0] + " " + triggerLogin()[1]);
        UserType user = DB.validate(triggerLogin()[0], triggerLogin()[1]);
        if (user == user.USER) {
            MainFrame mainFrame = new MainFrame();
            mainFrame.switchPanel(new MainMenu());
            JFrame parenFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            parenFrame.dispose();
        } else if (user == user.ADMIN) {
            AdminPage adminPage = new AdminPage();
            adminPage.setVisible(true);
            JFrame parenFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            parenFrame.dispose();
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    private void SelamatDatangTeksActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SelamatDatangTeksActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_SelamatDatangTeksActionPerformed

    private void Loginusername1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Loginusername1ActionPerformed
        // TODO add your handling code here:
        System.out.println(triggerLogin()[0]);
    }// GEN-LAST:event_Loginusername1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
        System.out.println(triggerLogin()[1]);
    }// GEN-LAST:event_jPasswordField1ActionPerformed

    private void SelamatDatangTeks2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SelamatDatangTeks2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_SelamatDatangTeks2ActionPerformed

    private String[] triggerLogin() {
        return new String[] {
                Loginusername1.getText().trim(), new String(jPasswordField1.getPassword()).trim()
        };
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Loginusername1;
    private javax.swing.JTextField SelamatDatangTeks;
    private javax.swing.JTextField SelamatDatangTeks2;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables

    public void show() {

    }
}
