/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projekbasdat;

import javax.swing.JFrame;

/**
 *
 * @author ACER
 */
public class TambahDataAdmin extends javax.swing.JFrame {

    /**
     * Creates new form TambahDataAdmin
     */
    public TambahDataAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SelamatDatangTeks = new javax.swing.JTextField();
        SelamatDatangTeks2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Loginusername2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Loginusername3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Loginusername4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Loginusername6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Loginusername7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Loginusername8 = new javax.swing.JTextField();
        btBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SelamatDatangTeks.setFont(new java.awt.Font("Javanese Text", 2, 14)); // NOI18N
        SelamatDatangTeks.setText("Masukkan Secara Rinci dan Benar");
        SelamatDatangTeks.setBorder(null);
        SelamatDatangTeks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelamatDatangTeksActionPerformed(evt);
            }
        });

        SelamatDatangTeks2.setFont(new java.awt.Font("Javanese Text", 1, 24)); // NOI18N
        SelamatDatangTeks2.setText("Tambah Data Mobil");
        SelamatDatangTeks2.setBorder(null);
        SelamatDatangTeks2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelamatDatangTeks2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 27, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 27, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));

        jLabel3.setText("Nama");

        Loginusername2.setForeground(new java.awt.Color(204, 204, 204));
        Loginusername2.setText("Masukkan di sini...");
        Loginusername2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Loginusername2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Tahun");

        Loginusername3.setForeground(new java.awt.Color(204, 204, 204));
        Loginusername3.setText("Masukkan di sini...");
        Loginusername3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Loginusername3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Kepemilikan");

        Loginusername4.setForeground(new java.awt.Color(204, 204, 204));
        Loginusername4.setText("Masukkan di sini...");
        Loginusername4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Loginusername4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Kursi");

        Loginusername6.setForeground(new java.awt.Color(204, 204, 204));
        Loginusername6.setText("Masukkan di sini...");
        Loginusername6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Loginusername6ActionPerformed(evt);
            }
        });

        jLabel8.setText("Lokasi ID");

        Loginusername7.setForeground(new java.awt.Color(204, 204, 204));
        Loginusername7.setText("Masukkan di sini...");
        Loginusername7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Loginusername7ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Selanjutnya");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Lokasi Dealer");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pune", "Hyderabad", "Ahmedabad",
                "Bangalore", "Kochi", "Mumbai", "Chennai", "Kolkata", "Coimbatore", "Delhi", "Jaipur" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Harga");

        Loginusername8.setForeground(new java.awt.Color(204, 204, 204));
        Loginusername8.setText("Masukkan di sini...");
        Loginusername8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Loginusername8ActionPerformed(evt);
            }
        });

        btBack.setText("Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btBack, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(Loginusername4,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 240,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(SelamatDatangTeks,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(SelamatDatangTeks2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(174, 174, 174))
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(Loginusername3,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 240,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Loginusername2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 240,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel9)
                                                        .addComponent(Loginusername8,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 240,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5))
                                                .addGap(49, 49, 49)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7)
                                                        .addComponent(Loginusername6,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 240,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel8)
                                                        .addComponent(Loginusername7,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 240,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jComboBox1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 240,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(55, 55, 55)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(SelamatDatangTeks2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SelamatDatangTeks, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(Loginusername2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Loginusername3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Loginusername8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel5))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel7)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(Loginusername6,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(74, 74, 74))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel8)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(Loginusername7,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Loginusername4, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31,
                                        Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btBack)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelamatDatangTeksActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SelamatDatangTeksActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_SelamatDatangTeksActionPerformed

    private void SelamatDatangTeks2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SelamatDatangTeks2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_SelamatDatangTeks2ActionPerformed

    private void Loginusername2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Loginusername2ActionPerformed
        // TODO add your handling code here:
        TemporaryData.getInstance().add(Loginusername2.getText());
    }// GEN-LAST:event_Loginusername2ActionPerformed

    private void Loginusername3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Loginusername3ActionPerformed
        // TODO add your handling code here:
        TemporaryData.getInstance().add(Loginusername3.getText());
    }// GEN-LAST:event_Loginusername3ActionPerformed

    private void Loginusername8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Loginusername8ActionPerformed
        // TODO add your handling code here:
        TemporaryData.getInstance().add(Loginusername8.getText());
    }// GEN-LAST:event_Loginusername8ActionPerformed

    private void Loginusername4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Loginusername4ActionPerformed
        // TODO add your handling code here:
        TemporaryData.getInstance().add(Loginusername4.getText());
    }// GEN-LAST:event_Loginusername4ActionPerformed

    private void Loginusername6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Loginusername6ActionPerformed
        // TODO add your handling code here:
        TemporaryData.getInstance().add(Loginusername6.getText());
    }// GEN-LAST:event_Loginusername6ActionPerformed

    private void Loginusername7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Loginusername7ActionPerformed
        // TODO add your handling code here:
        TemporaryData.getInstance().add(Loginusername7.getText());
    }// GEN-LAST:event_Loginusername7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Loginusername2ActionPerformed(null);
        Loginusername3ActionPerformed(null);
        Loginusername8ActionPerformed(null);
        Loginusername4ActionPerformed(null);
        Loginusername6ActionPerformed(null);
        Loginusername7ActionPerformed(null);
        TambahDataEngine tambahDataEngine = new TambahDataEngine();
        tambahDataEngine.setVisible(true);
        TemporaryData.getInstance().display();
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jComboBox1ActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TemporaryData.getInstance().deleteAll();
        AdminPage adminPage = new AdminPage();
        adminPage.setVisible(true);

    }// GEN-LAST:event_btBackActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Loginusername2;
    private javax.swing.JTextField Loginusername3;
    private javax.swing.JTextField Loginusername4;
    private javax.swing.JTextField Loginusername6;
    private javax.swing.JTextField Loginusername7;
    private javax.swing.JTextField Loginusername8;
    private javax.swing.JTextField SelamatDatangTeks;
    private javax.swing.JTextField SelamatDatangTeks2;
    private javax.swing.JButton btBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
