/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projekbasdat;

/**
 *
 * @author ACER
 */
public class TambahDataEngine extends javax.swing.JFrame {

    /**
     * Creates new form TambahDataEngine
     */
    public TambahDataEngine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SelamatDatangTeks = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SelamatDatangTeks2 = new javax.swing.JTextField();
        Loginusername2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Loginusername6 = new javax.swing.JTextField();
        Loginusername3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Loginusername7 = new javax.swing.JTextField();
        Loginusername4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Loginusername1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Loginusername5 = new javax.swing.JTextField();
        btBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SelamatDatangTeks.setFont(new java.awt.Font("Javanese Text", 2, 14)); // NOI18N
        SelamatDatangTeks.setText("Masukkan Secara Rinci dan Benar");
        SelamatDatangTeks.setBorder(null);
        SelamatDatangTeks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelamatDatangTeksActionPerformed(evt);
            }
        });

        jLabel3.setText("Mesin");

        SelamatDatangTeks2.setFont(new java.awt.Font("Javanese Text", 1, 24)); // NOI18N
        SelamatDatangTeks2.setText("Tambah Data Mesin");
        SelamatDatangTeks2.setBorder(null);
        SelamatDatangTeks2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelamatDatangTeks2ActionPerformed(evt);
            }
        });

        Loginusername2.setForeground(new java.awt.Color(204, 204, 204));
        Loginusername2.setText("Masukkan di sini...");
        Loginusername2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Loginusername2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Transmission");

        jLabel4.setText("Mileage");

        Loginusername6.setForeground(new java.awt.Color(204, 204, 204));
        Loginusername6.setText("Masukkan di sini...");
        Loginusername6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Loginusername6ActionPerformed(evt);
            }
        });

        Loginusername3.setForeground(new java.awt.Color(204, 204, 204));
        Loginusername3.setText("Masukkan di sini...");
        Loginusername3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Loginusername3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Fuel");

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 27, Short.MAX_VALUE));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));

        jLabel5.setText("Power");

        Loginusername7.setForeground(new java.awt.Color(204, 204, 204));
        Loginusername7.setText("Masukkan di sini...");
        Loginusername7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Loginusername7ActionPerformed(evt);
            }
        });

        Loginusername4.setForeground(new java.awt.Color(204, 204, 204));
        Loginusername4.setText("Masukkan di sini...");
        Loginusername4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Loginusername4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Simpan");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 27, Short.MAX_VALUE));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));

        jLabel2.setText("ID");

        Loginusername1.setForeground(new java.awt.Color(204, 204, 204));
        Loginusername1.setText("Masukkan di sini...");
        Loginusername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Loginusername1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Kilometer");

        Loginusername5.setForeground(new java.awt.Color(204, 204, 204));
        Loginusername5.setText("Masukkan di sini...");
        Loginusername5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Loginusername5ActionPerformed(evt);
            }
        });

        btBack.setText("Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel5,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jPanel4,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(btBack, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel4)
                                                                                        .addComponent(Loginusername3,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                240,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jLabel3)
                                                                                        .addComponent(Loginusername2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                240,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jLabel2)
                                                                                        .addComponent(Loginusername1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                240,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel7)
                                                                                        .addComponent(Loginusername6,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                240,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jLabel8)
                                                                                        .addComponent(Loginusername7,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                240,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jLabel5)
                                                                                        .addComponent(Loginusername4,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                240,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel6)
                                                                                        .addComponent(Loginusername5,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                240,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(0, 0, Short.MAX_VALUE))))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGap(165, 165, 165)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(SelamatDatangTeks,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(SelamatDatangTeks2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(174, 174, 174)))))
                                .addGap(40, 40, 40)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(SelamatDatangTeks2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btBack))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(SelamatDatangTeks, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel5)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(Loginusername4,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel7)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(Loginusername6,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        40,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(74, 74, 74))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel8)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(Loginusername7,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        40,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(Loginusername1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(Loginusername2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel4)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(Loginusername3,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Loginusername5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32,
                                                        Short.MAX_VALUE)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26))
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelamatDatangTeksActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SelamatDatangTeksActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_SelamatDatangTeksActionPerformed

    private void SelamatDatangTeks2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SelamatDatangTeks2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_SelamatDatangTeks2ActionPerformed

    private void Loginusername2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Loginusername2ActionPerformed
        // TODO add your handling code here:
        TemporaryData.getInstance().add(Loginusername2.getText());
    }// GEN-LAST:event_Loginusername2ActionPerformed

    private void Loginusername6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Loginusername6ActionPerformed
        // TODO add your handling code here:
        TemporaryData.getInstance().add(Loginusername6.getText());
    }// GEN-LAST:event_Loginusername6ActionPerformed

    private void Loginusername3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Loginusername3ActionPerformed
        // TODO add your handling code here:
        TemporaryData.getInstance().add(Loginusername3.getText());
    }// GEN-LAST:event_Loginusername3ActionPerformed

    private void Loginusername7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Loginusername7ActionPerformed
        // TODO add your handling code here:
        TemporaryData.getInstance().add(Loginusername7.getText());
    }// GEN-LAST:event_Loginusername7ActionPerformed

    private void Loginusername4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Loginusername4ActionPerformed
        // TODO add your handling code here:
        TemporaryData.getInstance().add(Loginusername4.getText());
    }// GEN-LAST:event_Loginusername4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Loginusername1ActionPerformed(null);
        Loginusername2ActionPerformed(null);
        Loginusername3ActionPerformed(null);
        Loginusername5ActionPerformed(null);
        Loginusername4ActionPerformed(null);
        Loginusername6ActionPerformed(null);
        Loginusername7ActionPerformed(null);
        TemporaryData.getInstance().display();
        // TemporaryData.getInstance().display();
    }// GEN-LAST:event_jButton1ActionPerformed

    private void Loginusername1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Loginusername1ActionPerformed
        // TODO add your handling code here:
        TemporaryData.getInstance().add(Loginusername1.getText());
    }// GEN-LAST:event_Loginusername1ActionPerformed

    private void Loginusername5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Loginusername5ActionPerformed
        // TODO add your handling code here:
        TemporaryData.getInstance().add(Loginusername5.getText());
    }// GEN-LAST:event_Loginusername5ActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TemporaryData.getInstance().deleteAll();
        AdminPage adminPage = new AdminPage();
        adminPage.setVisible(true);
    }// GEN-LAST:event_btBackActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Loginusername1;
    private javax.swing.JTextField Loginusername2;
    private javax.swing.JTextField Loginusername3;
    private javax.swing.JTextField Loginusername4;
    private javax.swing.JTextField Loginusername5;
    private javax.swing.JTextField Loginusername6;
    private javax.swing.JTextField Loginusername7;
    private javax.swing.JTextField SelamatDatangTeks;
    private javax.swing.JTextField SelamatDatangTeks2;
    private javax.swing.JButton btBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
